### ISSUE TITLE
Doubt - msg: Product details not available

### ISSUE THREAD

**Issue by mmicoe** [201949/godot-google-play-billing-7#2]
Hi again,
I'm testing the plugin.
1. When I press the purchase button, workflow does not display and I get the msg: Product details not available

`@UsedByGodot
    public void purchase(String productId, String type, String accountId, String profileId) {
        this.obfuscatedAccountId = accountId;
        this.obfuscatedProfileId = profileId;

        if (!productDetailsCache.containsKey(productId)) {
            emitSignal("purchase_error", BillingClient.BillingResponseCode.SERVICE_DISCONNECTED, "Product details not available");
            return;
        }`

Condition **productDetailsCache.containsKey(productId))** is validated as false and return.

I don't understand what I'm doing wrong. It is not an issue. Maybe Google Play console?
Using my old code library works fine! The code is the same, not updates in library 6.
Maybe Cache problem?

Note1: **_on_product_details_query_error** does not activate!
Thanks!

**Comment by 201949** [comment]
Hello Mauro,

If you would like to contact me directly, here is my email address: magikelle.studio@gmail.com or 201949@gmail.com. I will be able to respond more promptly if you provide more materials. Since I do not see any issues in the plugin itself, it seems that you may have not created the necessary product in Google Console or may not be using the plugin correctly.

Additionally, I wanted to inform you that I have prepared a new release of the plugin, in which logging of operations has been added.

At the same time, I'd like to point out that you can initiate logging to determine which products are available for purchase:

```
func _on_product_details_query_completed(sku_details):
	print("Product details query completed: " + str(sku_details))
	for available_sku in sku_details:
		purchasable_inapp[available_sku.productId] = available_sku
		print("Available SKU: ", available_sku)
```
This code will help you track the available products for purchase.

Best regards,
Mike, from Magikelle Studio

**Comment by 201949** [comment]
The issue could not be reproduced.
